global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:2112","localhost:2113","host.docker.internal:2112","host.docker.internal:2113"]