proto:
 protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
	api/v1/controller/controller.proto

plugin:
	go build -o ./plugin/greeter ./plugin/greeter.go