global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9091","host.docker.internal:9091"]
  - job_name: fed-test
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="host"}'
    static_configs:
      - targets: ["localhost:9091","host.docker.internal:9091"]