version: '3.5'

services:
  hacking:
    container_name: my-service
    image: krehermann/go-plugin-prom
    build:
      context: ../../
      dockerfile: Dockerfile
    # Note that the keystore import allows us to submit transactions
    # immediately because addresses are specified when starting the
    # parity/geth node to be prefunded with eth.
    entrypoint: /bin/sh -c "bin/cli server start"
    restart: always
    ports:
      # grpc server
      - 50051:50051
      # prom endpoints
      - 2112-2200:2112-2200

  prometheus-embedded:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # command:
    #  - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9091:9091'
    entrypoint: /bin/sh -c "prometheus --web.listen-address="0.0.0.0:9091" --config.file=/etc/prometheus/prometheus.yml"
