global:
  scrape_interval: 10s

scrape_configs:
  - job_name: host
    static_configs:
      - targets: ["host.docker.internal:2112"]
  - job_name: 'plugin-targets'
    http_sd_configs:
      - url: "http://host.docker.internal:2112/sd_config"
        refresh_interval: 10s