global:
  scrape_interval: 10s

rule_files:
  - /etc/prometheus/prometheus_rules.yml

scrape_configs:
  - job_name: plugins
    static_configs:
      - targets: ["host.docker.internal:2112"]
    http_sd_configs:
      - url: "http://host.docker.internal:2112/sd_config"
        refresh_interval: 10s

  - job_name: legacy
    static_configs:
      - targets: ["host.docker.internal:2113"]
